Parameters:
  Environment:
    Type: String

Resources:
  TutorialVPC:
    Type: AWS::EC2::VPC
    Properties:
      CdirBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: cfn-cicd
        - Key: Environment
          Value: !Sub ${Environment}
